[package]
name = "an-monkey-lang"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
dialoguer = "0.11.0"
thiserror = "1.0.50"

[dev-dependencies]
insta = "1.34.0"

#[profile.dev.package]
#insta.opt-level = 3
#similar.opt-level = 3
